// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvh7JUkMQSLLphpsl3mrK7rilgcu0pbsw',
    appId: '1:391705535917:web:f0d7fdbe13aa1fbc0f2d24',
    messagingSenderId: '391705535917',
    projectId: 'taptrendfrenchise',
    authDomain: 'taptrendfrenchise.firebaseapp.com',
    storageBucket: 'taptrendfrenchise.appspot.com',
    measurementId: 'G-HMNY6C6LZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTKX8h9BM_lmy_IVvAeH7hV8g0GOSmMzY',
    appId: '1:391705535917:android:66b9a2c78190746d0f2d24',
    messagingSenderId: '391705535917',
    projectId: 'taptrendfrenchise',
    storageBucket: 'taptrendfrenchise.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhLpFM6pIMjqQdSK8oSlYWz_FH8AUxyIQ',
    appId: '1:391705535917:ios:b1a40af5cd841f4d0f2d24',
    messagingSenderId: '391705535917',
    projectId: 'taptrendfrenchise',
    storageBucket: 'taptrendfrenchise.appspot.com',
    iosBundleId: 'com.example.franchise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhLpFM6pIMjqQdSK8oSlYWz_FH8AUxyIQ',
    appId: '1:391705535917:ios:fff4181015177ae00f2d24',
    messagingSenderId: '391705535917',
    projectId: 'taptrendfrenchise',
    storageBucket: 'taptrendfrenchise.appspot.com',
    iosBundleId: 'com.example.franchise.RunnerTests',
  );
}
